name: Test summary example

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Create reports directory
        run: mkdir -p ./reports/jest-stare
      - name: Run tests and generate report
        run: npm test -- --reporters=default --reporters=jest-junit --reporters=jest-stare
      - name: List report directory contents
        run: ls -la ./reports/jest-stare
      - name: Compile TypeScript
        run: npx tsc
      - name: Send Slack Notification
        run: node dist/sendSlackNotification.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
