name: Test summary example

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate report
        run: npm test -- --json --outputFile=ctrf-report.json
      - name: Send Slack Notification for Results
        run: npx slack-ctrf results ctrf-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Notification for Flaky Tests
        run: npx slack-ctrf flaky ctrf-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
