name: Test summary example

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Create reports directory
        run: mkdir -p ./reports/jest-stare
      - name: Run tests and generate report
        run: npm test -- --reporters=default --reporters=jest-junit --reporters=jest-stare
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: jest-stare-report
          path: ./reports/jest-stare
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: your-slack-channel
          SLACK_COLOR: good
          SLACK_MESSAGE: "Jest tests have completed. Check the detailed report [here](./reports/jest-stare/index.html)."
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
