name: Test summary example

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate report
        run: npm test
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: your-slack-channel
          SLACK_COLOR: good
          SLACK_MESSAGE: "Jest test results"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          args: ./reports/junit.xml
